export const ERROR_CODES = [
  'MIC_PERMISSION_DENIED',
  'MIC_DEVICE_NOT_FOUND',
  'AUDIO_CONTEXT_FAILED',
  'AUDIO_RING_OVERRUN',
  'CROSS_ORIGIN_ISOLATION_MISSING',
  'MODEL_MANIFEST_INVALID',
  'MODEL_LICENSE_REJECTED',
  'MODEL_DOWNLOAD_FAILED',
  'MODEL_CHECKSUM_MISMATCH',
  'MODEL_STORAGE_QUOTA_EXCEEDED',
  'MODEL_OPERATOR_UNSUPPORTED',
  'WEBGPU_DEVICE_LOST',
  'INFERENCE_FAILED',
  'DECODER_LIMIT_REACHED',
  'VOCABULARY_ENTRY_INVALID',
  'VOCABULARY_LIMIT_EXCEEDED',
  'PROFILE_BASE_MODEL_MISMATCH',
  'PROFILE_CHECKSUM_MISMATCH',
  'ENROLLMENT_QUALITY_FAILED',
  'ENROLLMENT_STORAGE_FAILED',
  'ADAPTER_TRAINING_FAILED',
  'ADAPTER_REGRESSION_GATE_FAILED',
  'WORKER_CRASHED',
  'TRAINING_RUNTIME_UNSUPPORTED',
  'TRAINING_DIVERGED',
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

export const WARNING_CODES = [
  'SHARED_MEMORY_UNAVAILABLE',
  'WEBGPU_UNAVAILABLE',
  'WASM_THREADS_UNAVAILABLE',
  'PERSISTENT_STORAGE_UNAVAILABLE',
  'PROVIDER_BENCHMARK_FAILED',
  'PROVIDER_FALLBACK_USED',
  'PROFILE_INACTIVE_UNTIL_NEXT_UTTERANCE',
  'VOCABULARY_REVISION_PENDING',
] as const;

export type WarningCode = (typeof WARNING_CODES)[number];

export interface RecoverableError {
  readonly code: ErrorCode;
  readonly recoverable: boolean;
  readonly message: string;
  readonly recoveryStep: string;
}
