export const RUNTIME_STATES = [
  'BOOTING',
  'CHECKING_CAPABILITIES',
  'MODEL_NOT_INSTALLED',
  'LOADING_MODEL',
  'READY',
  'LISTENING',
  'FINALIZING',
  'ENROLLING',
  'ANALYZING_TAKE',
  'PROFILE_READY',
  'EVALUATING_PROFILE',
  'EXPORTING_PROFILE',
  'IMPORTING_PROFILE',
  'TRAINING_PROFILE',
  'RECOVERABLE_ERROR',
  'FATAL_ERROR',
] as const;

export type RuntimeState = (typeof RUNTIME_STATES)[number];

const allowedTransitions: Readonly<Record<RuntimeState, readonly RuntimeState[]>> = {
  BOOTING: ['CHECKING_CAPABILITIES', 'FATAL_ERROR'],
  CHECKING_CAPABILITIES: ['MODEL_NOT_INSTALLED', 'LOADING_MODEL', 'FATAL_ERROR'],
  MODEL_NOT_INSTALLED: ['LOADING_MODEL', 'RECOVERABLE_ERROR', 'FATAL_ERROR'],
  LOADING_MODEL: ['READY', 'MODEL_NOT_INSTALLED', 'RECOVERABLE_ERROR', 'FATAL_ERROR'],
  READY: ['LISTENING', 'ENROLLING', 'LOADING_MODEL', 'RECOVERABLE_ERROR', 'FATAL_ERROR'],
  LISTENING: ['FINALIZING', 'READY', 'RECOVERABLE_ERROR', 'FATAL_ERROR'],
  FINALIZING: ['READY', 'RECOVERABLE_ERROR', 'FATAL_ERROR'],
  ENROLLING: ['ANALYZING_TAKE', 'PROFILE_READY', 'READY', 'RECOVERABLE_ERROR', 'FATAL_ERROR'],
  ANALYZING_TAKE: ['ENROLLING', 'PROFILE_READY', 'RECOVERABLE_ERROR', 'FATAL_ERROR'],
  PROFILE_READY: [
    'EVALUATING_PROFILE',
    'EXPORTING_PROFILE',
    'IMPORTING_PROFILE',
    'TRAINING_PROFILE',
    'READY',
    'RECOVERABLE_ERROR',
    'FATAL_ERROR',
  ],
  EVALUATING_PROFILE: ['PROFILE_READY', 'READY', 'RECOVERABLE_ERROR', 'FATAL_ERROR'],
  EXPORTING_PROFILE: ['PROFILE_READY', 'RECOVERABLE_ERROR', 'FATAL_ERROR'],
  IMPORTING_PROFILE: ['PROFILE_READY', 'RECOVERABLE_ERROR', 'FATAL_ERROR'],
  TRAINING_PROFILE: ['EVALUATING_PROFILE', 'PROFILE_READY', 'RECOVERABLE_ERROR', 'FATAL_ERROR'],
  RECOVERABLE_ERROR: [
    'MODEL_NOT_INSTALLED',
    'LOADING_MODEL',
    'READY',
    'ENROLLING',
    'PROFILE_READY',
    'FATAL_ERROR',
  ],
  FATAL_ERROR: [],
};

export function canTransition(from: RuntimeState, to: RuntimeState): boolean {
  return allowedTransitions[from].includes(to);
}

export function assertTransition(from: RuntimeState, to: RuntimeState): RuntimeState {
  if (!canTransition(from, to)) {
    throw new Error(`Illegal runtime transition: ${from} -> ${to}`);
  }
  return to;
}
