from __future__ import annotations

import json
import math
import struct
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import TypedDict


class LogMelConfigJson(TypedDict):
    sampleRateHz: int
    melBinCount: int
    frameLengthMs: int
    frameShiftMs: int
    fftSize: int
    lowFreqHz: int
    highFreqHz: int
    dither: int
    snipEdges: bool
    logFloor: float


DEFAULT_LOG_MEL_CONFIG: LogMelConfigJson = {
    "sampleRateHz": 16_000,
    "melBinCount": 80,
    "frameLengthMs": 25,
    "frameShiftMs": 10,
    "fftSize": 512,
    "lowFreqHz": 20,
    "highFreqHz": 7_600,
    "dither": 0,
    "snipEdges": True,
    "logFloor": 1e-10,
}


@dataclass(frozen=True)
class ResolvedLogMelConfig:
    sample_rate_hz: int
    mel_bin_count: int
    frame_length_ms: int
    frame_shift_ms: int
    fft_size: int
    low_freq_hz: float
    high_freq_hz: float
    dither: float
    snip_edges: bool
    log_floor: float
    frame_length_samples: int
    frame_shift_samples: int
    power_bin_count: int


def resolve_config(config: LogMelConfigJson = DEFAULT_LOG_MEL_CONFIG) -> ResolvedLogMelConfig:
    sample_rate_hz = _positive_int(config["sampleRateHz"], "sampleRateHz")
    mel_bin_count = _positive_int(config["melBinCount"], "melBinCount")
    frame_length_ms = _positive_int(config["frameLengthMs"], "frameLengthMs")
    frame_shift_ms = _positive_int(config["frameShiftMs"], "frameShiftMs")
    fft_size = _positive_int(config["fftSize"], "fftSize")
    low_freq_hz = _non_negative_number(config["lowFreqHz"], "lowFreqHz")
    high_freq_hz = _positive_number(config["highFreqHz"], "highFreqHz")
    dither = _non_negative_number(config["dither"], "dither")
    log_floor = _positive_number(config["logFloor"], "logFloor")

    if dither != 0:
        raise ValueError("Reference fixture generation is deterministic; dither must be zero.")
    if not _is_power_of_two(fft_size):
        raise ValueError("fftSize must be a power of two.")

    frame_length_samples = round(sample_rate_hz * frame_length_ms / 1_000)
    frame_shift_samples = round(sample_rate_hz * frame_shift_ms / 1_000)
    if frame_length_samples <= 0 or frame_shift_samples <= 0:
        raise ValueError("Frame length and shift must map to positive sample counts.")
    if fft_size < frame_length_samples:
        raise ValueError("fftSize must be at least frameLengthSamples.")
    if high_freq_hz <= low_freq_hz or high_freq_hz > sample_rate_hz / 2:
        raise ValueError("highFreqHz must be above lowFreqHz and at or below Nyquist.")

    return ResolvedLogMelConfig(
        sample_rate_hz=sample_rate_hz,
        mel_bin_count=mel_bin_count,
        frame_length_ms=frame_length_ms,
        frame_shift_ms=frame_shift_ms,
        fft_size=fft_size,
        low_freq_hz=low_freq_hz,
        high_freq_hz=high_freq_hz,
        dither=dither,
        snip_edges=config["snipEdges"],
        log_floor=log_floor,
        frame_length_samples=frame_length_samples,
        frame_shift_samples=frame_shift_samples,
        power_bin_count=fft_size // 2 + 1,
    )


def extract_log_mel(
    samples: list[float], config_json: LogMelConfigJson = DEFAULT_LOG_MEL_CONFIG
) -> list[list[float]]:
    config = resolve_config(config_json)
    window = _hann_window(config.frame_length_samples)
    filter_bank = _mel_filter_bank(config)
    frame_count = 0
    if len(samples) >= config.frame_length_samples:
        frame_count = (len(samples) - config.frame_length_samples) // config.frame_shift_samples + 1

    frames: list[list[float]] = []
    for frame_index in range(frame_count):
        start = frame_index * config.frame_shift_samples
        frames.append(_compute_frame(samples, start, False, config, window, filter_bank))

    consumed = frame_count * config.frame_shift_samples
    pending = samples[consumed:]
    if not config.snip_edges and pending:
        frames.append(_compute_frame(pending, 0, True, config, window, filter_bank))

    return frames


def build_log_mel_fixture_bundle() -> dict[str, object]:
    fixtures = []
    for fixture in _fixture_specs():
        samples = _fixture_samples(fixture["name"], int(fixture["sampleCount"]))
        frames = extract_log_mel(samples, DEFAULT_LOG_MEL_CONFIG)
        fixtures.append(
            {
                "name": fixture["name"],
                "sampleCount": fixture["sampleCount"],
                "frameCount": len(frames),
                "melBinCount": DEFAULT_LOG_MEL_CONFIG["melBinCount"],
                "features": [[round(value, 6) for value in frame] for frame in frames],
            }
        )

    return {
        "description": "Python reference log-Mel fixtures; generated by tools/feature-reference.",
        "config": DEFAULT_LOG_MEL_CONFIG,
        "fixtures": fixtures,
    }


def write_log_mel_fixture_bundle(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(build_log_mel_fixture_bundle(), indent=2, sort_keys=True) + "\n")


def _fixture_specs() -> Iterable[dict[str, int | str]]:
    return [
        {"name": "silence", "sampleCount": 960},
        {"name": "impulse", "sampleCount": 960},
        {"name": "sine_440hz", "sampleCount": 1_600},
        {"name": "clipped_square", "sampleCount": 960},
    ]


def _fixture_samples(name: str, sample_count: int) -> list[float]:
    if name == "silence":
        return [0.0 for _ in range(sample_count)]
    if name == "impulse":
        samples = [0.0 for _ in range(sample_count)]
        samples[320] = 1.0
        return samples
    if name == "sine_440hz":
        return [
            _float32(0.5 * math.sin(2 * math.pi * 440 * index / 16_000))
            for index in range(sample_count)
        ]
    if name == "clipped_square":
        return [1.0 if (index // 40) % 2 == 0 else -1.0 for index in range(sample_count)]
    raise ValueError(f"Unknown fixture name: {name}")


def _compute_frame(
    samples: list[float],
    start: int,
    zero_pad: bool,
    config: ResolvedLogMelConfig,
    window: list[float],
    filter_bank: list[list[float]],
) -> list[float]:
    real = [0.0 for _ in range(config.fft_size)]
    imag = [0.0 for _ in range(config.fft_size)]
    for sample_index in range(config.frame_length_samples):
        source_index = start + sample_index
        if source_index < len(samples):
            sample = samples[source_index]
        elif zero_pad:
            sample = 0.0
        else:
            raise ValueError("Cannot compute an unpadded frame without enough samples.")
        real[sample_index] = sample * window[sample_index]

    _fft_in_place(real, imag)
    power = [
        real[bin_index] ** 2 + imag[bin_index] ** 2 for bin_index in range(config.power_bin_count)
    ]

    frame = []
    for mel_bin in range(config.mel_bin_count):
        energy = 0.0
        for bin_index, weight in enumerate(filter_bank[mel_bin]):
            energy += weight * power[bin_index]
        frame.append(math.log(max(energy, config.log_floor)))
    return frame


def _hann_window(frame_length_samples: int) -> list[float]:
    if frame_length_samples == 1:
        return [1.0]
    return [
        0.5 - 0.5 * math.cos(2 * math.pi * index / (frame_length_samples - 1))
        for index in range(frame_length_samples)
    ]


def _mel_filter_bank(config: ResolvedLogMelConfig) -> list[list[float]]:
    low_mel = _hz_to_mel(config.low_freq_hz)
    high_mel = _hz_to_mel(config.high_freq_hz)
    mel_points = [
        low_mel + (high_mel - low_mel) * index / (config.mel_bin_count + 1)
        for index in range(config.mel_bin_count + 2)
    ]
    hz_points = [_mel_to_hz(point) for point in mel_points]
    bin_frequencies = [
        bin_index * config.sample_rate_hz / config.fft_size
        for bin_index in range(config.power_bin_count)
    ]
    filters: list[list[float]] = []

    for mel_bin in range(config.mel_bin_count):
        left_hz = hz_points[mel_bin]
        center_hz = hz_points[mel_bin + 1]
        right_hz = hz_points[mel_bin + 2]
        left_width = center_hz - left_hz
        right_width = right_hz - center_hz
        weights = []
        for frequency_hz in bin_frequencies:
            weight = 0.0
            if left_hz <= frequency_hz <= center_hz:
                weight = (frequency_hz - left_hz) / left_width
            elif center_hz < frequency_hz <= right_hz:
                weight = (right_hz - frequency_hz) / right_width
            weights.append(max(0.0, weight))
        filters.append(weights)

    return filters


def _fft_in_place(real: list[float], imag: list[float]) -> None:
    size = len(real)
    bit_count = int(math.log2(size))
    for index in range(size):
        reversed_index = _reverse_bits(index, bit_count)
        if index < reversed_index:
            real[index], real[reversed_index] = real[reversed_index], real[index]
            imag[index], imag[reversed_index] = imag[reversed_index], imag[index]

    fft_size = 2
    while fft_size <= size:
        half_size = fft_size // 2
        table_step = size // fft_size
        for offset in range(0, size, fft_size):
            for index in range(half_size):
                angle = -2 * math.pi * (index * table_step) / size
                wr = math.cos(angle)
                wi = math.sin(angle)
                even_index = offset + index
                odd_index = even_index + half_size
                tr = wr * real[odd_index] - wi * imag[odd_index]
                ti = wr * imag[odd_index] + wi * real[odd_index]
                real_even = real[even_index]
                imag_even = imag[even_index]
                real[odd_index] = real_even - tr
                imag[odd_index] = imag_even - ti
                real[even_index] = real_even + tr
                imag[even_index] = imag_even + ti
        fft_size *= 2


def _reverse_bits(value: int, bit_count: int) -> int:
    reversed_value = 0
    for bit in range(bit_count):
        reversed_value = (reversed_value << 1) | ((value >> bit) & 1)
    return reversed_value


def _hz_to_mel(hz: float) -> float:
    return 2_595 * math.log10(1 + hz / 700)


def _mel_to_hz(mel: float) -> float:
    return 700 * (10 ** (mel / 2_595) - 1)


def _float32(value: float) -> float:
    return struct.unpack("f", struct.pack("f", value))[0]


def _positive_int(value: int, name: str) -> int:
    if not isinstance(value, int) or value <= 0:
        raise ValueError(f"{name} must be a positive integer.")
    return value


def _positive_number(value: float, name: str) -> float:
    if not isinstance(value, int | float) or not math.isfinite(value) or value <= 0:
        raise ValueError(f"{name} must be a positive number.")
    return float(value)


def _non_negative_number(value: float, name: str) -> float:
    if not isinstance(value, int | float) or not math.isfinite(value) or value < 0:
        raise ValueError(f"{name} must be a non-negative number.")
    return float(value)


def _is_power_of_two(value: int) -> bool:
    return value > 0 and value & (value - 1) == 0
